### ISSUE TITLE
`igraph.lib` is not available in Windows pacakge

### ISSUE THREAD

**Issue by vtraag** [conda-forge/igraph-feedstock#31]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

The Windows build does not make the `igraph.lib` available, preventing downstream packages from compiling against this package on Windows.

Strangely enough, the [run in PR #30](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=304283&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5018) does install the `igraph.lib`, while the subsequent [run in the `master` branch](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=297260&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5742) does not install `igraph.lib`. Presumably, if `install.lib` would be installed, it would be picked up and installed correctly when doing `conda install igraph`.

@isuruf, could I ask for your help here?

**Comment by isuruf** [comment]
I've no idea what's going on. Latest master build log seems to indicate `igraph.lib` was installed.

**Comment by vtraag** [comment]
I think it might have been an older version of `cmake`. For some reason, [this faulty run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=297260&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5742) used version 3.19.6-h39d44d4_0, while [the run in PR #30](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=304283&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5018) used version 3.20.1-h39d44d4_0. The most recent [`master` run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=304306&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5018) which does correctly install `igraph.lib` also installed version 3.20.1-h39d44d4_0. Previous runs for version 0.9.1 (e.g. [this](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=297260&view=logs&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f&l=5742) one) also did not install `igraph.lib` and also used `cmake` version 3.19.6-h39d44d4_0.

**Comment by vtraag** [comment]
I cannot reproduce this locally, also not with that version of `cmake`. I am closing this, since at least the most recent version (0.9.2) does have a proper `igraph.lib` available.
