### ISSUE TITLE
Update windows compilers

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/igraph-feedstock#65]
Hey all

This feedstock is directly specifying `vs2017_{{ target_platform }}` as a dependency,
https://github.com/conda-forge/igraph-feedstock/blob/c1c60774ee9ab49fc75e62c4fc9f61dc72331161/recipe/meta.yaml#L24-L29

but should just rely on the `{{ compiler('c') }}` function to provide the correct compilers on windows. In particular, conda-forge has moved on to vs2019 as the default compiler a while ago already.

If you think you need vs2017, please let us know why (generally vs2019 and vs2022 should be fully compatible). If it's really necessary, please use the dedicated mechanism in `conda_build_config.yaml` for that, i.e.
```
c_compiler:     # [win]
  - vs2017      # [win]
cxx_compiler:   # [win]
  - vs2017      # [win]
```
as opposed to specifying it in `meta.yaml` directly

**Comment by vtraag** [comment]
Re-opened because of need to re-render: https://github.com/conda-forge/igraph-feedstock/pull/64#issuecomment-1925825034

**Comment by h-vetinari** [comment]
Thanks for the quick response!

You can see that it's already rerendered correctly if you look into the generated ci configuration:
https://github.com/conda-forge/igraph-feedstock/blob/89818fd79fafe2a70b31291f277b94c718f3f162/.ci_support/win_64_.yaml#L1-L2

**Comment by xylar** [comment]
Ah, great! That saves us some trouble!

**Comment by h-vetinari** [comment]
This is still used in the test requirements:
https://github.com/conda-forge/igraph-feedstock/blob/89818fd79fafe2a70b31291f277b94c718f3f162/recipe/meta.yaml#L59
